export const reduxTypes = {
    SET_AUTH_LOGIN: 'SET_AUTH_LOGIN',
    SET_AUTH_PASSWORD: 'SET_AUTH_PASSWORD',
    SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
    SET_AUTH_LOGGED_IN: 'SET_AUTH_LOGGED_IN',
    SET_AUTH_ERROR: 'SET_AUTH_ERROR',
}
