export const reduxTypes = {
    SET_AUTH_LOGIN: 'SET_AUTH_LOGIN',
    SET_AUTH_PASSWORD: 'SET_AUTH_PASSWORD',
    SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
    SET_AUTH_LOGGED_IN: 'SET_AUTH_LOGGED_IN',
    SET_AUTH_ERROR: 'SET_AUTH_ERROR',

    SET_SIGN_UP_MAIL: 'SET_SIGN_UP_MAIL',
    SET_SIGN_UP_LOGIN: 'SET_SIGN_UP_LOGIN',
    SET_SIGN_UP_NAME: 'SET_SIGN_UP_NAME',
    SET_SIGN_UP_PASSWORD_FIRST_TIME: 'SET_SIGN_UP_PASSWORD_FIRST_TIME',
    SET_SIGN_UP_PASSWORD_SECOND_TIME: 'SET_SIGN_UP_PASSWORD_SECOND_TIME',
    SET_SIGN_UP_MAIL_ERROR: 'SET_SIGN_UP_MAIL_ERROR',
    SET_SIGN_UP_LOGIN_ERROR: 'SET_SIGN_UP_LOGIN_ERROR',
    SET_SIGN_UP_PASSWORD_ERROR: 'SET_SIGN_UP_PASSWORD_ERROR',
    SET_SIGN_UP_SUCCESS: 'SET_SIGN_UP_SUCCESS',

    SET_HABITS: 'SET_HABITS',

    SET_ADD_HABIT_MODAL: 'SET_ADD_HABIT_MODAL',
    SET_HABIT_NAME_INPUT: 'SET_HABIT_NAME_INPUT',
    SET_HABIT_MEASURE_INPUT: 'SET_HABIT_MEASURE_INPUT',
    SET_NEW_HABIT_SUCCESS: 'SET_NEW_HABIT_SUCCESS',
    SET_NEW_HABIT_ERROR: 'SET_NEW_HABIT_ERROR',

    SET_DELETE_HABIT_MODAL: 'SET_DELETE_HABIT_MODAL',
    SET_DELETE_SUCCESS: 'SET_DELETE_SUCCESS',
}
